# Generated by Django 3.2.15 on 2022-10-13 11:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ManyToManyField(blank=True, default=blog.models.eng, to='blog.Language'),
        ),
    ]
