# Generated by Django 3.2.15 on 2022-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('lb', 'lightblue'), ('pb', 'pastelblue'), ('pp', 'pastelpurple'), ('sg', 'seagreen')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ManyToManyField(related_name='languages', to='blog.Language'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.Tag'),
        ),
    ]
