# Generated by Django 3.2.15 on 2022-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20221015_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('lb', 'lightblue'), ('pb', 'pastelblue'), ('pp', 'pastelpurple'), ('sg', 'seagreen'), ('ds', 'dark sky'), ('nb', 'navy blue'), ('lg', 'light grey')], default='pb', max_length=2),
        ),
    ]
