# Generated by Django 3.2.15 on 2022-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tag_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
