# Generated by Django 3.2.15 on 2022-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(choices=[('lb', 'lightblue'), ('pb', 'pastelblue'), ('pp', 'pastelpurple'), ('sg', 'seagreen'), ('ds', 'dark sky'), ('nb', 'navy blue'), ('lg', 'light grey'), ('dd', 'delve deeper special')], default='pb', max_length=2),
        ),
    ]
