# Generated by Django 3.2.15 on 2022-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_align',
            field=models.CharField(choices=[('c', 'align-center'), ('t', 'algin-top'), ('b', 'align-bottom')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='title_background',
            field=models.CharField(choices=[('no', 'none'), ('gr', 'grey'), ('bl', 'black'), ('wh', 'white')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='title_color',
            field=models.CharField(choices=[('wh', 'white'), ('lb', 'lightblue'), ('pb', 'pastelblue'), ('pp', 'pastelpurple'), ('sg', 'seagreen'), ('bl', 'inkblack')], default='bl', max_length=2),
        ),
    ]
