# Generated by Django 3.2.15 on 2022-10-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('tex', 'text-based post'), ('pic', 'picture-based post'), ('art', 'artwork')], default='tex', max_length=3),
        ),
    ]
