# Generated by Django 3.2.15 on 2022-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_orientation',
            field=models.CharField(choices=[('h', 'horizontal'), ('v', 'vertical')], default='v', max_length=1),
        ),
    ]
